### ISSUE TITLE
Removing the HREF attribute in My Stack Tab

### ISSUE THREAD

**Issue by capturemathan** [dantehemerson/dantecalderon.dev#658]
Kudos to a wonderful website 🎉, currently the `My Stack` Tab contains the required icons of the stack-tools and upon hovering gives details as a tooltip but upon clicking the icon (eg) Javascript, every icon has an HREF set to `google.com` and redirects the user to the same. This is unnecessary and can be removed as TOOLTIP gives the required info about the hovered-icon.

**Comment by dantehemerson** [comment]
@capturemathan Thank you for your suggestion :smiley:
